### ISSUE TITLE
New Philips Hue bridge

### ISSUE THREAD

**Issue by BasEmmen** [michaelrcarroll/script.kodi.hue.ambilight#10]
Before i switch to the new 2015 Philips Hue bridge, do you know if this bridge is compatible with the SDK where you rely on?
http://www2.meethue.com/en-us/productdetail/philips-hue-bridge

**Comment by michaelrcarroll** [comment]
I personally do not yet have a new bridge, but my understanding is that it *should* work just fine. API don't care whether or not it is a Bridge v1 or v2.

I have not yet tested the changes made to the auto-connection, so that's the only thing. I'll close this one, but feel free to open an issue if you run into trouble.
