### ISSUE TITLE
Wont detect movie start

### ISSUE THREAD

**Issue by FritzTeufel** [michaelrcarroll/script.kodi.hue.ambilight#21]
Hi!
When i start kodi the extension sets the lights to the preset undimmed brightness.
When i start a movie nothing happens, if i pause the movie still nothing, but when i press play again the lights dim to the dimmed brightness (zero). When i pause again the lights dim to the paused brightness. 
When i stop the movie the light returns to the undimmed state.
If i start another movie the same thing repeats itself.

debug log : http://pastebin.com/SSSJ6qGG

Im using the new bridge, with hue white lights.

**Comment by FritzTeufel** [comment]
Ohh i just have to read the code :) 
it was the pauseafterrefreshchange 
even i had the "Adjust display refresh rate" turned off, the "Pause during refresh rate change" wasnt set to Off. Please include a few words about this in the Installation instructions.
And thanks for the great addon.

**Comment by Deanmv** [comment]
What were your Kodi video settings for this?  I am getting this happen as well with 0.8b2.  Any input one what the video settings within Kodi should be for this @michaelrcarroll?

My issue is that when I start the video it does nothing, when I then pause the video and press play again the lights dim as it should.  It seems like the checking for state "started" isn't working correctly.

In 0.7 the started line was 
`if state == "started":`

Whereas in 0.8 it is 
` if (state == "started" and hue.pauseafterrefreshchange == 0)`

Which is where I *think* the issue is.
