### ISSUE TITLE
please consider Hyperion

### ISSUE THREAD

**Issue by BETEP-ok** [michaelrcarroll/script.kodi.hue.ambilight#33]
please note that there can be people (like me) willing to use both- Hue lights and Hyperion ambilight
https://github.com/tvdzwan/hyperion

it would be really nice not to run into compatibility issue)

PS (realize it is a very early stage) consider also extending support for other formats. HUE is not the only and much overpriced solution. There are more cheap smart light systems on the market.

**Comment by michaelrcarroll** [comment]
@BETEP-ok Thanks for your suggestion. Hyperion looks like a nicely done ambilight system. Especially since we're seeing issues with the color accuracy and performance of the ambilight functionality, perhaps i could utilize it in the future to help offline the ambilight, but that'll take some doing. I'll close and file this away for a reference, and consider it for the future.

Regarding the choice for hue: right now it's a very popular lighting system (even if pricey), and more importantly, it's the one that I have to use, test, and debug. If you'd like to work on support for other lighting platforms, feel free to fork and modify to fit your needs.
